stages:
  prepare:
    cmd: python -m iris_classification.prepare
    deps:
    - data/raw/
    - iris_classification/prepare.py
    outs:
    - data/prepared/test.csv
    - data/prepared/train.csv
  train:
    cmd: python -m iris_classification.train
    deps:
    - data/prepared/train.csv
    - iris_classification/train.py
    outs:
    - model/iris_model.joblib
